### PR TITLE
Enable some constants that are actually available on redox

### PR DESCRIPTION
**Pull request by coolreader18**
`libc` recently added more constants for redox, so some of the cfgs can be removed.

### CODE REVIEW

**Review by Thomasdezeeuw — COMMENTED** [review]
You've remove the `all` feature on a lot constants and functions.

```
#[cfg(all(feature = "all", not(target_os = "redox")))]
```
Should become:
```
#[cfg(feature = "all")]
```

**Comment by coolreader18** [comment]
Ohh, I figured that those were only there because redox didn't have them, but I assume windows doesn't either? I'll fix that

**Comment by coolreader18** [comment]
I don't think the macos failure is related to my changes

**Review by Thomasdezeeuw — APPROVED** [review]

**Comment by Thomasdezeeuw** [comment]
Thanks @coolreader18. So you know, this is the v0.4.x version which is currently released and doesn't have a release date yet.

**Comment by coolreader18** [comment]
Yup, I was going to backport these redox fixes to 0.3 next, as it currently doesn't compile.

**Pull request merged**
